### ISSUE TITLE
Source of loopback request error and Blocks WP REST API

### ISSUE THREAD

**Issue by nettles-sync** [emotionLoop/visualCaptcha-WordPress#12]
Errors generated in the Site Healthcheck report, isolated the issue to this plugin. Activated twenty-seventeen theme and only this plugin, same issue. Removed from site, but wanted to pass along as a courtesy if anyone is still maintaining or planning to use.

**Comment by BrunoBernardino** [comment]
Thanks @nettles-sync, if more people report this I can consider looking into it.
