### ISSUE TITLE
Is this plugin still being maintained?

### ISSUE THREAD

**Issue by olpo24** [emotionLoop/visualCaptcha-WordPress#13]

**Comment by BrunoBernardino** [comment]
Hey @olpo24, @desirepath41 are responsible for it and I’d assume they’re planning on maintaining it, otherwise is there an issue you’re seeing?

**Comment by desirepath41** [comment]
Hi @olpo24 unfortunately due to unforeseen circumstances, we will not be updating or maintaining the plugin
